### ISSUE TITLE
New hook: useMap

### ISSUE THREAD

**Issue by xiaochengzi6** [vmejs/vmejs#13]
**hook使用场景？**

使用 `useState()`  去保存 map 类型的数据时，直接操作修改 map 数据比如 `map.set()` 并不会使组件更新而恰恰又需要监听 map 数据变更，使用 `useMap` 修改 map 数据它的功能相对于 `useState()` 修改普通数据格式一样 

**hook用法？** 

~~~ts
const [map, {
  set,
  setAll,
  del,
  reset,
  get
}] = useMap()

// agreement && returnValue
interface Actions<K, T> {
  set: (key: K, val: T) => void;
  setAll: (newMap: Iterable<readonly [K, T]>) => void;
  del: (key: K) => void;
  reset: () => void;
  get: (key: K) => void;
}

function useMap<K, T>(initialValue?: Iterable<readonly [K, T]>): [Iterable<readonly [K, T]>, Actions<K, T>]
~~~

**补充说明？**
无

**Comment by jeddygong** [comment]
@xiaochengzi6 PR Welcome，同时可以在 @vmejs/vue-hooks 和 @vmejs/react-hooks 中也可补充哈

**Comment by SymphonyIceAttack** [comment]
这是为了弥补react对map更新的缺陷是吗？

**Comment by xiaochengzi6** [comment]
> 

Hi, 首先我们要考虑一个使用场景比如动态的获取数据(数据的获取毫无规律)我们通常使用 `useState`去存储数据，介于每次获取的数据都要缓存起来所以这里使用 `Map`的数据格式去缓存数据
~~~ts
const [map, setMap] = useState(() => new Map())
useEffect(() => {
  // 这里获得动态的数据 date
  map.set(date)
})
~~~
这里是使用 map 直接对数据进行保存 ok 这是毫无问题的 但是 现在我要依赖于 map 中数据的变化去生成组件亦或者其他东西
~~~ts
const instruct = useMemo(() => {
  let arr = []
 map.forEach(data => arr.push(data))
 return arr 
}, [map])
~~~
这里只运行了一次，关键的是 map 的地址毫无变化，但是数据产生了变动
你可以有疑惑 为什么不使用`setMap()`呢
~~~js
setMap((oldMap) => {
  let target = [[date], ...oldMap]
  return new Map(target)
})
~~~
这里需要这样使用既要保留原来的数据又要缓存 Map 这样的数据结构 这一块的逻辑就完全可以抽离出来，在业务逻辑中减少这些不必要的代码，而且如果其他地方也需要使用它 就不得不在多个位置粘贴类似代码

几乎这就是 hook 思路 一旦有重复or通用的性质 就选择将其抽离出来
