### ISSUE TITLE
New hook: useCountArray

### ISSUE THREAD

**Issue by xiaochengzi6** [vmejs/vmejs#14]
**hook使用场景？**

考虑这样的场景 点击新增后会新增组件 持续的点击会持续的新增, 点击减少就会减少一个组件，持续点击就会持续的删除，在此基础上可以指定删除某个组件，这样的操作通常是需要去维护一个数组往其中添加数值(使用数组可以很好的记录组件添加的顺序)，然后遍历数组生成组件 使用 useCountArray 来完成这样的工作

**hook用法？**
~~~ts
type Options = {
  length?: number; // 初始长度
  step?: number; // 步距
  max?: number; // 最大值
  min?: number; // 最小值
}

const [
  array,
  {
    inc,
    del,
    dec,
    clear,
    reset
  }
] = useCountArray()

function useCountArray(options?: Options): [any[], Actions]
~~~

**补充说明？**
无

**Comment by jeddygong** [comment]
这个在原生中都有类似的优化，感觉使用场景不大，你感觉如何

**Comment by xiaochengzi6** [comment]
> 这个在原生中都有类似的优化，感觉使用场景不大，你感觉如何

那就先关闭这个 issue 吧 这个我考虑不周
